name: test
on:
  pull_request:
    branches:
      - main
env:
  envName: ${{ (github.ref_name == 'production' || "latest") || (github.ref_name == 'main' || "latest") }}
jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      envName: ${{ env.envName }}
    
  test:
    runs-on: ubuntu-${{ needs.init.outputs.envName }}
    needs: ['init']
    steps:
      run: hey-${{ needs.init.outputs.envName }}.yaml apply && exit 4
